### ISSUE TITLE
Regarding data generation of 'train.npz', 'valid.npz', 'test.npz'

### ISSUE THREAD

**Issue by niconical** [SYSU-Workflow-Lab/DeepScaler#1]
非常感谢团队的代码开源工作，我正在尝试复现该代码，我想请问一下`python data_process.py`之后可以获得实时数据，那么`main.py`中的`train.npz,test.npz,valid.npz`数据是如何拆分得到的？

Thank you very much for the team's code open source work. I am trying to reproduce the code. I would like to ask if `python data_process.py` can obtain real-time data, then `train.npz, test.npz,valid.npz`, etc. in `main.py` How is the data split?

**Comment by niconical** [comment]
Solve it!

**Comment by llllittlelos** [comment]
请问是分别收集数据，然后命名为 'train.npz', 'valid.npz', 'test.npz'吗
