### ISSUE TITLE
Missing configurations for the model training

### ISSUE THREAD

**Issue by nzalik** [SYSU-Workflow-Lab/DeepScaler#3]
I appreciate your repository and am trying to reproduce your experimentation.

At the section **4. Export the well-trained model** Which parameters are the default parameters for training the model?

The link you provided to us **More parameter information please refer to main.py. The models exported after running the file are stored in the [model_states](https://github.com/SYSU-Workflow-Administrator/DeepScaler/tree/main/model_states).** redirect to a not found page.

Thank you in advance for you anwser.

**Comment by mengchy** [comment]
Thank you very much for identifying this issue. The redirect link is indeed incorrect. However, you can find the relevant parameter settings within the "main.py" file located in the project's root directory. Additionally, the exported models can be found in the "model_states" subdirectory. @nzalik
