### ISSUE TITLE
There seems to be some error in the code

### ISSUE THREAD

**Issue by jmLee4** [SYSU-Workflow-Lab/DeepScaler#4]
I would appreciate it if you could answer some of the puzzles I encountered while reading the code. Thanks~

+ The `mem` indicator was not collected, but is was needed when aggregating tensors, and `metrics[3]` ware used, which is another indicator
https://github.com/SYSU-Workflow-Lab/DeepScaler/blob/95eb126eaab1416f17bf5597efbf56735fb19fd7/data_process.py#L193-L195

+ When converting `np.ndarray` to `torch.tensor`, both `listreq` and `listmem` used the wrong `listres`
https://github.com/SYSU-Workflow-Lab/DeepScaler/blob/95eb126eaab1416f17bf5597efbf56735fb19fd7/data_process.py#L243-L247

By the way, there is a lot of redundant code in **data_process.py** that can be reconstructed through a `for` loop

**Comment by mengchy** [comment]
Thank you for reporting this issue. It has been resolved in commit `1dd4e33`. @jmLee4
