### ISSUE TITLE
AdapGLA.pkl 模型参数不匹配

### ISSUE THREAD

**Issue by jmLee4** [SYSU-Workflow-Lab/DeepScaler#5]
您好，加载 model_stats/AdapGLA/AdapGLA.pkl 文件进 AdapGLA 模型时报错，缺失参数且存在许多非预期的参数
![image](https://github.com/user-attachments/assets/15159e31-d8a4-491f-82f6-dc606e2da8da)

经过尝试后发现该 checkpoint 应该加载进 AdapGLT 模型；更换后报错信息变更为Tensor的形状不匹配
不知道是不是我操作有问题，想向您咨询一下这个该如何解决

![image](https://github.com/user-attachments/assets/45035cb3-4ebc-42e8-85ef-d07c054e690e)

**Comment by ssJokerss** [comment]
您好，建议您依据自身的具体实验状况展开详细分析，确保数据张量能够准确对齐。您不妨进行 debug 调试，以便更精准地发现并解决问题。
